name: warehouse
description: Renew Project cause of some error



version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11


  flutter_slidable: ^1.3.0
  double_back_to_close_app: ^2.1.0  
  flutter_datetime_picker: ^1.5.1
  csv: ^5.0.1
  toast: ^0.3.0

  
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
 





flutter:
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Regular.ttf
        - asset: assets/Lato-Bold.ttf
          weight: 700
  
  
  
  
  
  
  
  
